image: awsservicebroker/aws-servicebroker:beta
imagePullPolicy: Always
authenticate: false # true
tls:
  cert:
  key:
deployClusterServiceBroker: true
deployNamespacedServiceBroker: false
aws:
  region: eu-central-1
  bucket: awsservicebroker
  key: templates/latest
  s3region: us-east-1
  tablename: awssb
  accesskeyid: ""
  secretkey: ""
  targetaccountid: ""
  targetrolename: ""
  vpcid: "awssb"
  existingSecret: ""
  accesskeyidName: "accesskeyid"
  secretkeyName: "secretkey"
brokerconfig:
  verbosity: 10
  brokerid: awsservicebroker
  prescribeoverrides: true
annotations: {}
clusterDomain: cluster.local
